### ISSUE TITLE
Graphs for pyTorch version

### ISSUE THREAD

**Issue by TheodoreGalanos** [altosaar/variational-autoencoder#10]
Hello! Thanks for your implementation it was really helpful to try and set it up on my own dataset!

Was wondering if you had a script somewhere that includes the sampling graphs for the pyTorch version, as I feel they were only included in the TF code.

Thanks in advance!

Kind regards,
Theodore.

**Comment by jaanaltosaar** [comment]
Thanks Theodore—I'm not sure what you mean by sampling graphs. Can you give me an example or point to the place in the code in the TF version?

**Comment by TheodoreGalanos** [comment]
@altosaar apologies I think I misphrased it, I meant if there was code for pyTorch that samples and visualizes the prior distribution of the model in order to generate the visualizations that you show in your blog. I hope that's not too much, it's fine if they aren't available!

**Comment by jaanaltosaar** [comment]
Ah I understand—if you need it feel free to write it (it should mirror the tensorflow version; ping me if you get stuck!), and submit a pull request :)
