### ISSUE TITLE
Adaptation to CNN

### ISSUE THREAD

**Issue by TheodoreGalanos** [altosaar/variational-autoencoder#11]
Hello again!

Was wondering if you had any advice as to what it would take to turn this into a CVAE implementation. Would it be enough to change the VAE part, or would the impact trickle down to all other networks (mainly thinking of the flow.py models).

Thanks in advance!

Kind regards,
Theodore.

**Comment by jaanaltosaar** [comment]
Good idea—yeah you could replace the inference and generative networks by the corresponding convolutional versions.
