### ISSUE TITLE
unable to open file: name = 'dat/binarized_mnist.hdf5'

### ISSUE THREAD

**Issue by w32zhong** [altosaar/variational-autoencoder#13]
Anyone direct me to where this file should be downloaded or tell me how to generate it? Thank you in advance!

**Comment by w32zhong** [comment]
I see the note in source file:
> run https://github.com/altosaar/proximity_vi/blob/master/get_binary_mnist.py to download binary MNIST file

Thanks anyway.

**Comment by w32zhong** [comment]
BTW. this project code is ugly (magic numbers everywhere, `num_no_improvement > 5`?), too much unnecessary dependencies.

**Comment by jaanaltosaar** [comment]
Thanks @t-k- ! 

I agree the code isn't as nice as it could be. 

Feel free to do a code review on this commit and I will do my best to improve the code quality :)

https://github.com/altosaar/variational-autoencoder/commit/c78cb3f7208dccd029112265518c38abb4abda55

**Comment by w32zhong** [comment]
@altosaar Hi, I just start learning deep learning in my part time, I am not able to review your code on model aspects, but from a beginner's perspective, I feel your code is not as clean as other vae implementations, such as [this one](https://github.com/t-k-/Variational_Auto-Encoder) and [this one](https://github.com/ethanluoyc/pytorch-vae), the complexity and dependencies causes many troubles when I just want to get a simple VAE running so that I can understand better from looking through "verified code". It is very exhaustive after I spend hours to simply correctly run your code (including download a h5 format MNIST different from what I have on the disk), and it turns out this implementation trains much longer than the others, like my [mentioned one](https://github.com/t-k-/Variational_Auto-Encoder), which produces better decoded image after just a few epochs. I understand the lengthy code and its complexity may implies comprehensive features or some other advantages, but please understand, me being a beginner chooses to make comments only from code simplicity and training result. If you think there are some advantages compared to that repo, please let me know and I will appreciate your teaching and apologize for my comments.

**Comment by jaanaltosaar** [comment]
Sounds good, thanks for the comments! I agree it can be improved. I'll try to think about what is best to prioritize here.

**Comment by jaanaltosaar** [comment]
@t-k- have you looked at the pytorch version? https://github.com/altosaar/variational-autoencoder/blob/master/train_variational_autoencoder_pytorch.py 

I think it is easier to understand. I'm happy to try to remove further dependencies if it's still confusing. Please let me know!

**Comment by jaanaltosaar** [comment]
@t-k- I incorporated the script to download the data: https://github.com/altosaar/variational-autoencoder/blob/master/train_variational_autoencoder_pytorch.py#L156 

Hopefully that's one less step to worry about :)

**Comment by w32zhong** [comment]
@altosaar Thanks for pointing out that, and for the update! I believe these changes will facilitate many learners! I feel bad about saying things about your code now :face_with_head_bandage:. I know it can be hard to get code right at the beginning and at the same time sharing your code and trying to benefit the community. Sorry for my bursting out frustration that day, I had too much that day trying to get a version working.

**Comment by w32zhong** [comment]
BTW, the code looks much cleaner now. Unfortunately I do not have much time to have a careful look today. Will check out later. Thanks for your work.

**Comment by jaanaltosaar** [comment]
No worries at all I appreciate hearing your frustrations. Definitely feel free to follow up if you notice anything else! Thank you for your feedback 👍
