### ISSUE TITLE
Interpretation of each dimension on the shape

### ISSUE THREAD

**Issue by CXX1113** [altosaar/variational-autoencoder#17]
In the train_variational_autoencoder_pytorch.py 
```
if __name__ == '__main__':
...
    for step, batch in enumerate(cycle(train_data)):
        x = batch[0].to(device)
        model.zero_grad()  # Sets gradients of all model parameters to zero.
        variational.zero_grad()
        z, log_q_z = variational(x) 
        log_p_x_and_z = model(z, x)  
        # average over sample dimension
        elbo = (log_p_x_and_z - log_q_z).mean(1) 
...
```
The reason is not mean (**0**) or mean(**2**),because:
log_p_x_and_z's and log_q_z's shape both are 3D. According to my understanding of ELBO, the interpretation of each dimension on the shape is as follows:
(batch_size, sample_times, lantent_size)
In your code, the sample_times of the lantent variables is once, so shape[1] = 1.
So, mean(**1**) is an estimate of the ELBO expectation.

Is my understanding correct?

**Comment by jaanaltosaar** [comment]
Good question! That's correct.

By default the variational distribution returns a single sample. But you could use more samples to reduce the gradient variance. 

I tried to make it clearer by adding this explicitly:

```
    z, log_q_z = variational(x, n_samples=1)
    log_p_x_and_z = model(z, x)
    # average over sample dimension
    elbo = (log_p_x_and_z - log_q_z).mean(1)
```

https://github.com/altosaar/variational-autoencoder/blob/master/train_variational_autoencoder_pytorch.py#L229
