### ISSUE TITLE
Possible error in loss function

### ISSUE THREAD

**Issue by cc20002002** [altosaar/variational-autoencoder#19]
The KL divergence part of your loss is inconsistent with your documentation in https://jaan.io/what-is-variational-autoencoder-vae-tutorial/ .

In the documentation, you said use the posterior q(z|x) but in the code, you applied prior~q(z).

https://github.com/altosaar/variational-autoencoder/blob/96337fa367e720bd59da6979b64b2a526e96cfc1/train_variational_autoencoder_tensorflow.py#L132

ELBO_i(\theta, \phi) = \mathbb{E}{q_\theta(z\mid x_i)}[\log p_\phi(x_i\mid z)] - \mathbb{KL}(q_\theta(z\mid x_i) \mid\mid p(z)).ELBO ​i ​​ (θ,ϕ)=Eq ​θ ​​ (z∣x ​i ​​ )[logp ​ϕ ​​ (x ​i ​​ ∣z)]−KL(q ​θ ​​ (z∣x ​i ​​ )∣∣p(z)).

**Comment by cc20002002** [comment]
I just realise the q_z is actually posterior q_z given x. I suggest you rename the variable to something similar to  q_z_given_x.

**Comment by jaanaltosaar** [comment]
That sounds like a good idea - thanks! Feel free to submit a pull request :)
