### ISSUE TITLE
the expected_log_likelihood is not a expected value, but only an log likelihood

### ISSUE THREAD

**Issue by jiongjiongli** [altosaar/variational-autoencoder#20]
May I confirm line 133 in train_variational_autoencoder_tensorflow.py:
 
```
 expected_log_likelihood = tf.reduce_sum(p_x_given_z.log_prob(x),
                                          [1, 2, 3])
```
It seems the reduce_sum returns not an expected value, but only a log likelihood.

**Comment by jaanaltosaar** [comment]
Good question—it is an expectation (a Monte Carlo estimate), but using a single sample. The expectation is over q_z, as `q_z.sample()` only draws a single sample:  https://github.com/altosaar/variational-autoencoder/blob/96337fa367e720bd59da6979b64b2a526e96cfc1/train_variational_autoencoder_tensorflow.py#L104
