### ISSUE TITLE
A question regarding q_z

### ISSUE THREAD

**Issue by natank1** [altosaar/variational-autoencoder#27]
I follow the torch version.
Elbo = Eq[log(P(x}z) -Kl(q(z|x)||P(z))]
Denote Log(P(x|z) -KL(Q(Z|X)||p(Z) as t(z,x) we have
Elbo= Eq(t(z,x)) 

For each point you  perform calculate only the t(z,x). Namely for a batch of 16 samples each point t(z}xi) get the same weight , how come?

**Comment by jaanaltosaar** [comment]
Thanks @natank1 ! 

This is computing a Monte Carlo estimate of `ELBO= E_q[t(z,x)]`, using `N` samples, where `N` might be 16, and every sample gets the same weight (the Monte Carlo estimate is computed as the average of the samples). Please email me if that is unclear!

**Comment by natank1** [comment]
Sure, my mistake
