### ISSUE TITLE
Follow up on why inputs must be between 0 and 1

### ISSUE THREAD

**Issue by garenkwan** [altosaar/variational-autoencoder#30]
I was wondering why the inputs must be scaled to be between 0 and 1. Ref: #25 

Reading your blog article, it seems to me that there is no such requirement imposed mathematically. (Or is there?)

**Comment by jaanaltosaar** [comment]
This is more an artefact of optimization for normalizing flow models - this paper should help: https://arxiv.org/pdf/2006.09347.pdf
