### ISSUE TITLE
 no attribute 'stochastic_graph'

### ISSUE THREAD

**Issue by parsifal9** [altosaar/variational-autoencoder#4]
Hi Jaan,
there seem to have been some changes in tensorflow. I get the error

 module 'tensorflow.contrib.bayesflow' has no attribute 'stochastic_graph

tensorflow-1.5.0
python 3.6 

Bye
parsifal9

**Comment by jaanaltosaar** [comment]
Thanks for letting me know @parsifal9 – fixed: https://github.com/altosaar/variational-autoencoder/commit/877bf1b2fc4933ef04ea6bd92ca1a0e28fc583dd

Good thing stochastic_graph is removed now. I think it makes the code simpler. Please let me know if there's anything else :)
